force-app/main/default/objects/TriggerBypass__mdt/TriggerBypass__mdt.object-meta.xml
<CustomObject>
    <description>This is an example implementation of bypassing trigger action via a boolean on the trigger handler class, using Custom Metadata to store settings.</description>
    <label>Trigger Bypass</label>
    <pluralLabel>Trigger Bypasses</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerBypass__mdt/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If True, this TriggerHandler class will be bypassed (its actions will not occur).</description>
    <inlineHelpText>If True, this TriggerHandler class will be bypassed (its actions will not occur).</inlineHelpText>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerBypass__mdt/fields/TriggerHandlerMethodName__c.field-meta.xml
<CustomField>
    <fullName>TriggerHandlerMethodName__c</fullName>
    <description>The name of the trigger handler and method to bypass (or not).
Recommended naming convention: [TriggerHandlerClasss].[MethodName], e.g., AccountTriggerHandler.afterUpdate
Note that this field is 255 characters, to account for a possible future change in maximum length allowed by Salesforce.</description>
    <inlineHelpText>The name of the trigger handler and method to bypass (or not).
Recommended naming convention: [TriggerHandlerClasss].[MethodName], e.g., AccountTriggerHandler.afterUpdate</inlineHelpText>
    <label>TriggerHandlerMethodName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TriggerService.cls
/**
 * Example implementation of a Service class to determine if a Trigger should bepypassed.
 * @created 2022-11-04: Richard Moore
 */
public class TriggerService {
    
    /**
     * Basic method to check whether bypass is requested for the specified trigger handler.
     * Calls inner method for common functionality using dependency injection
     * @param triggerHandlerName (String): Name of the trigger handler class
     * @return boolean: TRUE if disabled
 	 * @created 2022-11-04: Richard Moore
     */
    public static Boolean isBypassEnabled(String triggerHandlerMethodName){
        List<TriggerBypass__mdt> bypassRecords = [SELECT Id, Bypass__c
                                                 FROM TriggerBypass__mdt
                                                 WHERE TriggerHandlerMethodName__c =:triggerHandlerMethodName
                                                 LIMIT 1];
        return isBypassEnabledOrDefault(bypassRecords);
    }
    
    /**
     * Dependency Injection method to allow functional testing without using production metadata
     * @param bypassRecords (List<TriggerBypass__mdt>): List of records with expected size of 0 or 1
     * @return boolean: TRUE if disabled
     * @created 2022-11-04: Richard Moore
     */
    @testVisible
    private static Boolean isBypassEnabledOrDefault(List<TriggerBypass__mdt> bypassRecords){
        return bypassRecords.isEmpty() ? false : bypassRecords[0].Bypass__c;
    }
}