force-app/main/default/objects/TriggerBypass__mdt/TriggerBypass__mdt.object-meta.xml
<CustomObject>
    <description>This is an example implementation of bypassing trigger action via a boolean on the trigger handler class, using Custom Metadata to store settings.</description>
    <label>Trigger Bypass</label>
    <pluralLabel>Trigger Bypasses</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerBypass__mdt/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If True, this TriggerHandler class will be bypassed (its actions will not occur).</description>
    <inlineHelpText>If True, this TriggerHandler class will be bypassed (its actions will not occur).</inlineHelpText>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerBypass__mdt/fields/TriggerHandlerMethodName__c.field-meta.xml
<CustomField>
    <fullName>TriggerHandlerMethodName__c</fullName>
    <description>The name of the trigger handler and method to bypass (or not).
Recommended naming convention: [TriggerHandlerClasss].[MethodName], e.g., AccountTriggerHandler.afterUpdate
Note that this field is 255 characters, to account for a possible future change in maximum length allowed by Salesforce.</description>
    <inlineHelpText>The name of the trigger handler and method to bypass (or not).
Recommended naming convention: [TriggerHandlerClasss].[MethodName], e.g., AccountTriggerHandler.afterUpdate</inlineHelpText>
    <label>TriggerHandlerMethodName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TriggerServiceTest.cls
@IsTest
private class TriggerServiceTest {
    
    @IsTest
    private static void itShouldQueryMetadata(){
        String TRIGGER_HANDLER_METHOD_NAME = 'itShouldQueryMetadata';
        
        Test.startTest();
        Boolean actual = TriggerService.isBypassEnabled(TRIGGER_HANDLER_METHOD_NAME);
        Test.stopTest();
        
        List<TriggerBypass__mdt> bypassRecords = [SELECT Id, Bypass__c
                                                  FROM TriggerBypass__mdt
                                                  WHERE TriggerHandlerMethodName__c =:TRIGGER_HANDLER_METHOD_NAME
                                                  LIMIT 1];
        
        Boolean expected = false;
        if (!bypassRecords.isEmpty()){
            expected = bypassRecords[0].Bypass__c;
        }
        
        Assert.areEqual(expected, actual, 'The value should be returned accurately, defaulting to false');
    }
    
    @IsTest
    private static void itShouldDefaultToFalseWhenNoMetadataRecord(){        
        Test.startTest();
        Boolean actual = TriggerService.isBypassEnabledOrDefault(new List<TriggerBypass__mdt>());
        Test.stopTest();
        
        Assert.isFalse(actual, 'The value should default to false when no metadata record');
    }
    /*
    @IsTest
    private static void itShouldDefaultToFalseWhenNoMetadataRecord2(){
        
        TriggerBypass__mdt exampleRecord = new TriggerBypass__mdt();
        exampleRecord.TriggerHandlerMethodName__c='itShouldDefaultToFalseWhenNoMetadataRecord';
        exampleRecord.Bypass__c = true;
        
        Test.startTest();
        Boolean actual = TriggerService.isBypassEnabledOrDefault(null);
        Test.stopTest();
        
        Assert.areEqual(expected, actual, 'The value should be returned accurately, defaulting to false');
    }*/

}